POST  http://localhost:5000/api/register
Content-Type: application/json

{
  "name": "john",
  "email": "johndoe@gmail.com",
  "password": "2345"
}

###
POST http://localhost:5000/api/login
content-type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "2345"

}

### 
POST http://localhost:5000/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2Njg4Njc5MiwianRpIjoiODNiMzRhNmUtYzlmZi00M2Q0LTkxYTgtOTBkYWE0NzE5OThiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSJ9LCJuYmYiOjE2NjY4ODY3OTIsImV4cCI6MTY2Njg4NzY5Mn0.i5m1tBmj0aNyYGN9tb2QQ39qDjuwtH2VEFmJjuAxPvw

{
  "title": "Learn React",
  "description": "Learn React and Redux",
  "complete": false 
  
}
